<?php


/**
 * Implements hook_form_alter()
 */
function ext_form_form_alter(&$form, &$form_state, $form_id)
{
  // отключить HTML5 валидацию на всех формах
  $form['#attributes']['novalidate'] = '';

  if (strpos($form_id, 'webform_client_form') === 0) {
    $form["actions"]["submit"]["#attributes"]["class"][] = 'btn-brand';
    $form["actions"]["submit"]["#attributes"]["class"][] = 'btn-wide';
  }

  // на странице поиска заменить текст кнопки на иконку
  if (strpos($form["#id"], 'views-exposed-form-catalog-page') === 0) {
    $form["submit"]["#value"] = '<i class="icon icon-04"></i>';
    $form["submit"]['#attributes'] = ['class' => ['btn', 'btn-brand', 'btn-direction']];
    $form["submit"]['#theme_wrappers'] = ['button_icon'];
  }
}

function ext_form_search_form($form, $form_state)
{
  $form['k'] = [
    '#type' => 'textfield',
    '#attributes' => ['placeholder' => t('search')],
    '#prefix' => '<div class="form-item input-group">'
  ];
  $form['submit'] = [
    '#type' => 'submit',
    '#value' => '<i class="icon icon-04"></i>',
    '#attributes' => ['class' => ['btn', 'btn-brand']],
    '#theme_wrappers' => ['button_icon'],
    '#suffix' => '</div>'
  ];

  return $form;
}
function ext_form_search_form_submit($form, $form_state)
{
  drupal_goto('search', ['query' => ['k' => $form_state['values']['k']]]);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_form_form_node_form_alter(&$form, &$form_state, $form_id)
{
  if ($form["#form_id"] == 'product_node_form') {

    // уточнить текст кнопок в форме
    if (!empty($form["field_item_descriptions"]["und"])) {
      foreach($form["field_item_descriptions"]["und"] as &$value) {
        if (isset($value["remove_button"]["#value"])) {
          $value["remove_button"]["#value"] = 'Удалить описание';
        }
      }
      $form["field_prep_specs"]["und"]["add_more"]["#value"] = 'Добавить описание';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function ext_form_form_webform_client_form_6_alter(&$form, &$form_state)
{
  // заполнить поле текста, если он присутствует в ссылке
  if (isset($_GET['message'])) {
    $form["submitted"]["message"]["#default_value"] = check_plain($_GET['message']);
  }

  // ajax обновление формы отправки заявки
  $form['#prefix'] = '<div id="' . $form["#id"] . '-wrapper">';
  $form['#suffix'] = '</div>';

  $form['actions']['submit']['#ajax'] = [
    'callback' => 'ext_form_webform_client_form_6_ajax_callback',
    'wrapper' => $form["#id"] . '-wrapper',
  ];

  $form["#submit"][] = 'ext_form_rebuild_submit';
}
function ext_form_webform_client_form_6_ajax_callback($form, $form_state)
{
  if (!empty($form["#submission"])) {
    $form['submitted']['complete'] = [
      '#markup' => '<div class="complete">' .
        '<h4>' . t('Message been sent.') . '</h4>' .
        '<p>' . t('We will contact you as soon as possible.') . '</p>' .
        '</div>',
    ];
  }
  // сбросить сообщение после обновления страницы
  unset($_SESSION["webform_confirmation"]);

  return $form;
}
function ext_form_rebuild_submit($form, &$form_state)
{
  $form_state['rebuild'] = TRUE;
}
