<?php

/**
 * Implements hook_menu_alter()
 */
function ext_node_menu_alter(&$items)
{
  // убрать материалы с Главной
  $items['node']['page callback'] = 'ext_node_empty_front_page_callback';

  // Кнопка "Удалить" в локальные задачи материала
  // http://xandeadx.ru/blog/drupal/339
  $items['node/%node/delete']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
}

/**
 * menu callback
 * убрать материалы с главной
 */
function ext_node_empty_front_page_callback()
{
  drupal_set_title('');
  return [];
}

/**
 * Implements hook_preprocess_page().
 */
function ext_node_preprocess_page(&$vars)
{
  if ($GLOBALS['theme'] == 'mineral') {
    if (arg(0) == 'node' && isset($vars['node'])) {
      // Сформировать Баннер в шапке
      $banner_uri = null;

      // для страницы Препарата
      if ($vars['node']->type == 'product') {
        $vars['is_title_on'] = false;
        $vars['banner_title'] = t('Mineral nutrition');
      }

      if ($banner_uri) {
        $vars['is_banner_on'] = true;
        $vars['banner_url'] = file_create_url($banner_uri);
        $vars['banner_mobile_url'] = image_style_url('banner_mobile', $banner_uri);
      }
    }
  }

}

/**
 * Implements hook_preprocess_node().
 */
function ext_node_preprocess_node(&$vars)
{
  $node = $vars['node'];

  // ссылки всегда скрыты
  hide($vars["content"]["links"]);

  // -- Общие для всех видов просмотра -----------------------------------------
  // -- Изображения
  // так как в некоторых типах нод изображения выводятся в слайдере,
  // то соберём свой массив для вывода
  $images = [];
  if (!empty($vars['content']['field_images']['#items'])) {
    foreach ($vars['content']['field_images']['#items'] as $key => $file) {
      $images[] = $vars['content']['field_images'][$key];
    }
  }
  elseif (!empty($vars['content']['field_image'])) {
    $images[] = $vars['content']['field_image'][0];
  }
  $vars['images'] = $images;

  if ($node->type == 'product') {
    $product_info = sec_catalog_get_product_info($node->nid);
    $vars['title'] = $product_info['title'];
    $vars['label'] = $product_info['label'];
    $vars['brand'] = $product_info['brand']['label'];
  }

  // -- Полный вид просмотра ---------------------------------------------------
  if ($vars['view_mode'] == 'full') {
    if ($node->type == 'product') {
      $product_info = sec_catalog_get_product_info($node->nid);

      hide($vars["content"]["field_item_components"]);
      hide($vars["content"]["field_item_descriptions"]);
      hide($vars["content"]["field_item_formulation"]);
      $vars['product_info'] = $product_info;

      // кнопка Поделиться
      // -- Полная ссылка для социальных шар
      $url = url('node/' . $node->nid, ['absolute' => true]);
      $title = t('About @site product', ['@site' => variable_get('site_name')]);
      $text = t('A link to the information at the website of @site.', ['@site' => variable_get('site_name')]);
      $vars['share_btn'] = theme('share_btn', ['url' => $url, 'title' => $title, 'text' => $text]);

      $brand = empty($product_info['brand']['label']) ? '' : $product_info['brand']['label'] . ' ';
      $message = t('Contact me about your product') . ' «' . $brand . $product_info['label'] . '».';
      $vars['product_buy_btn'] = l(t('Buy'), 'node/6',
        ['attributes' => ['class' => ['btn', 'btn-brand', 'btn-lg', 'btn-wide']], 'query' => ['message' => $message]]
      );

      // подготовить таблицу с регламентами
      if ($product_info['reglaments']) {

        $header = [
          'Культура',
          'Доза препарата, <span class="nowrap">л/га</span>',
          'Способ и время применения',
          'Расход рабочей жидкости, <span class="nowrap">л/га</span>',
        ];

        $rows = $spans = [];
        $ps_value = $ms_value = 0;
        $ps_count = $ms_count = 0;
        $ps_id = $ms_id = 0;
        foreach($product_info['reglaments'] as $id => $reglament) {
          if ($ps_value != $reglament['prep_spend']) {
            $ps_value = $reglament['prep_spend'];
            $ps_id = $id; $ps_count = 0;
          } else $ps_count++;
          if ($ms_value != $reglament['mix_spend']) {
            $ms_value = $reglament['mix_spend'];
            $ms_id = $id; $ms_count = 0;
          } else $ms_count++;
          if ($ps_count) $spans[$ps_id]['ps'] = $ps_count;
          if ($ms_count) $spans[$ms_id]['ms'] = $ms_count;
          $ps = $ps_count ? '' : ['data' => $reglament['prep_spend'], 'align' => 'center'];
          $ms = $ms_count ? '' : ['data' => $reglament['mix_spend'], 'align' => 'center'];

          $rows[$id]['0'] = $reglament['culture'];
          if ($ps) $rows[$id]['1'] = $ps;
          $rows[$id]['2'] = $reglament['application'];
          if ($ms) $rows[$id]['3'] = $ms;
        }
        foreach ($spans as $id => $value) {
          if (isset($value['ps'])) $rows[$id]['1']['rowspan'] = $value['ps']+1;
          if (isset($value['ms'])) $rows[$id]['3']['rowspan'] = $value['ms']+1;
        }

        $vars['reglaments_table'] = theme('table', array('header' => $header, 'rows' => $rows));
      }
    }
  }

}

/**
 * Implements hook_form_alter().
 */
function ext_node_form_alter(&$form, &$form_state, $form_id)
{
  if ($GLOBALS['theme'] != 'seven' && isset($form["revision_information"]["#access"])) {
    $form["revision_information"]["#access"] = false;
    $form["options"]["#weight"] = $form["author"]["#weight"] - 1;
  }
}

/**
 * Implements hook_form_FORMID_alter().
 */
function ext_node_form_node_form_alter(&$form, &$form_state)
{
  if (in_array($form["type"]["#value"], ['article', 'product'])) {
    // убрать неиспользуемые опции
    $form["options"]["sticky"]["#access"] = false;
    $form["author"]["#access"] = false;

    // изменить формат поля Body на "Редактор текста", если формат ранее не был установлен
    $lang = $GLOBALS['language']->language;
    if (isset($form["body"][$lang][0]["#type"]) && $form["body"][$lang][0]["#type"] == 'text_format' && !$form["body"][$lang][0]["#format"]) {
      $form["body"][$lang][0]["#format"] = 'filtered_html';
    }

    $form["actions"]["submit"]["#attributes"]['class'] = ['btn-primary'];
  }
}



